In [1]:
import pandas
import numpy
import matplotlib.pyplot as plt
import seaborn

In [2]:
df = pandas.read_csv('code_markdown_before_after_with_metadata_fast.csv')
df

,fileNames,cell_seq_num,cellType,_has_output,_output_contains_graphics,_output_contains_tables,_has_heading,has_tables,has_math,markdown_before,markdown_after,before_contains_heading,before_contains_tables,before_contains_math,after_contains_heading,after_contains_tables,after_contains_math
0,serve/light/00014130779110127e4663c5bea956ca98...,18,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
1,serve/light/00014130779110127e4663c5bea956ca98...,23,code,True,True,False,False,False,False,True,True,False,False,False,True,False,False
2,serve/light/00014130779110127e4663c5bea956ca98...,25,code,True,True,False,False,False,False,True,True,True,False,False,False,False,False
3,serve/light/00014130779110127e4663c5bea956ca98...,27,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
4,serve/light/00014130779110127e4663c5bea956ca98...,29,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208422,serve/light/fffd4c1669082d48e561ce5b1171a55472...,15,code,True,True,False,False,False,False,False,False,False,False,False,False,False,False
208423,serve/light/fffd885a4df5d69c9f709a216f25a91260...,18,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
208424,serve/light/fffe21dde7d18843cef438cd9eb13437de...,19,code,True,True,False,False,False,False,True,False,False,False,False,False,False,False
208425,serve/light/fffe21dde7d18843cef438cd9eb13437de...,21,code,True,True,False,False,False,False,False,True,False,False,False,False,False,False
208426,serve/light/fffe21dde7d18843cef438cd9eb13437de...,27,code,True,True,False,False,False,False,True,False,False,False,False,False,False,False

For all code cells containing image outputs, we possibly associate a description if table exists before the current cell if there's a markdown cell before it.

If a cell after the current cell contains a table and does not contain a heading, it is associated with the data.
If the cell contains a heading after the current cell, it is likely a switch in context.

In [3]:
df[(df['cellType'] == 'code') & (df['_has_output'] == True) & (df['_output_contains_graphics'] == True)]

,fileNames,cell_seq_num,cellType,_has_output,_output_contains_graphics,_output_contains_tables,_has_heading,has_tables,has_math,markdown_before,markdown_after,before_contains_heading,before_contains_tables,before_contains_math,after_contains_heading,after_contains_tables,after_contains_math
0,serve/light/00014130779110127e4663c5bea956ca98...,18,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
1,serve/light/00014130779110127e4663c5bea956ca98...,23,code,True,True,False,False,False,False,True,True,False,False,False,True,False,False
2,serve/light/00014130779110127e4663c5bea956ca98...,25,code,True,True,False,False,False,False,True,True,True,False,False,False,False,False
3,serve/light/00014130779110127e4663c5bea956ca98...,27,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
4,serve/light/00014130779110127e4663c5bea956ca98...,29,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208422,serve/light/fffd4c1669082d48e561ce5b1171a55472...,15,code,True,True,False,False,False,False,False,False,False,False,False,False,False,False
208423,serve/light/fffd885a4df5d69c9f709a216f25a91260...,18,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
208424,serve/light/fffe21dde7d18843cef438cd9eb13437de...,19,code,True,True,False,False,False,False,True,False,False,False,False,False,False,False
208425,serve/light/fffe21dde7d18843cef438cd9eb13437de...,21,code,True,True,False,False,False,False,False,True,False,False,False,False,False,False
208426,serve/light/fffe21dde7d18843cef438cd9eb13437de...,27,code,True,True,False,False,False,False,True,False,False,False,False,False,False,False

In [5]:
# Number of code cells matching the filter above but which do not have a heading after the current output.
noheading_after = df[(df['cellType'] == 'code') & (df['_has_output'] == True) & (df['_output_contains_graphics'] == True) & (df['after_contains_heading'] != True)]
noheading_after

,fileNames,cell_seq_num,cellType,_has_output,_output_contains_graphics,_output_contains_tables,_has_heading,has_tables,has_math,markdown_before,markdown_after,before_contains_heading,before_contains_tables,before_contains_math,after_contains_heading,after_contains_tables,after_contains_math
0,serve/light/00014130779110127e4663c5bea956ca98...,18,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
2,serve/light/00014130779110127e4663c5bea956ca98...,25,code,True,True,False,False,False,False,True,True,True,False,False,False,False,False
3,serve/light/00014130779110127e4663c5bea956ca98...,27,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
4,serve/light/00014130779110127e4663c5bea956ca98...,29,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
6,serve/light/00014130779110127e4663c5bea956ca98...,35,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208422,serve/light/fffd4c1669082d48e561ce5b1171a55472...,15,code,True,True,False,False,False,False,False,False,False,False,False,False,False,False
208423,serve/light/fffd885a4df5d69c9f709a216f25a91260...,18,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
208424,serve/light/fffe21dde7d18843cef438cd9eb13437de...,19,code,True,True,False,False,False,False,True,False,False,False,False,False,False,False
208425,serve/light/fffe21dde7d18843cef438cd9eb13437de...,21,code,True,True,False,False,False,False,False,True,False,False,False,False,False,False
208426,serve/light/fffe21dde7d18843cef438cd9eb13437de...,27,code,True,True,False,False,False,False,True,False,False,False,False,False,False,False

In [10]:
noheading_after[(noheading_after['markdown_before'] == True) | (noheading_after['markdown_after'] == True)]

,fileNames,cell_seq_num,cellType,_has_output,_output_contains_graphics,_output_contains_tables,_has_heading,has_tables,has_math,markdown_before,markdown_after,before_contains_heading,before_contains_tables,before_contains_math,after_contains_heading,after_contains_tables,after_contains_math
0,serve/light/00014130779110127e4663c5bea956ca98...,18,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
2,serve/light/00014130779110127e4663c5bea956ca98...,25,code,True,True,False,False,False,False,True,True,True,False,False,False,False,False
3,serve/light/00014130779110127e4663c5bea956ca98...,27,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
4,serve/light/00014130779110127e4663c5bea956ca98...,29,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
6,serve/light/00014130779110127e4663c5bea956ca98...,35,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208413,serve/light/fff7c4d4be623b2939969e02ef27227059...,23,code,True,True,False,False,False,False,True,True,True,False,False,False,False,False
208423,serve/light/fffd885a4df5d69c9f709a216f25a91260...,18,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
208424,serve/light/fffe21dde7d18843cef438cd9eb13437de...,19,code,True,True,False,False,False,False,True,False,False,False,False,False,False,False
208425,serve/light/fffe21dde7d18843cef438cd9eb13437de...,21,code,True,True,False,False,False,False,False,True,False,False,False,False,False,False
208426,serve/light/fffe21dde7d18843cef438cd9eb13437de...,27,code,True,True,False,False,False,False,True,False,False,False,False,False,False,False

In [22]:
noheading_after[(noheading_after['markdown_before'] == True) | (noheading_after['markdown_after'] == True)]['fileNames'].value_counts()

serve/light/72667ad2f073fa7925d83afaf7c912a4d27a4cf0.html    91
serve/light/931568140bb98f0ac04ba663174869aca591240a.html    80
serve/light/9eb0049bea949d24c754c47a74104615b87882a3.html    75
serve/light/332d582c84a2e0d056f95ad7bf7267108176e469.html    56
serve/light/0714a003ba1d70ad585c794e8eb707422c6281ce.html    51
                                                             ..
serve/light/34f112230c6457fe13d40efd75c8e2b29faa5a61.html     1
serve/light/34f0b7eadb696b7e9b8537c25a62e3df1fbb0dd1.html     1
serve/light/99f80c483fdaf805589b39b5d6b04f6eb43fda6d.html     1
serve/light/99fc7daf229041979df6eebe18757577d5f4a565.html     1
serve/light/7f0e454ae28b40c6e50279df15db354062959d6b.html     1
Name: fileNames, Length: 19028, dtype: int64

In [11]:
noheading_after[(noheading_after['markdown_before'] == True)]

,fileNames,cell_seq_num,cellType,_has_output,_output_contains_graphics,_output_contains_tables,_has_heading,has_tables,has_math,markdown_before,markdown_after,before_contains_heading,before_contains_tables,before_contains_math,after_contains_heading,after_contains_tables,after_contains_math
0,serve/light/00014130779110127e4663c5bea956ca98...,18,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
2,serve/light/00014130779110127e4663c5bea956ca98...,25,code,True,True,False,False,False,False,True,True,True,False,False,False,False,False
3,serve/light/00014130779110127e4663c5bea956ca98...,27,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
4,serve/light/00014130779110127e4663c5bea956ca98...,29,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
6,serve/light/00014130779110127e4663c5bea956ca98...,35,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208409,serve/light/fff6c4a56e1a630fa61b9bd5aa9adce411...,64,code,True,True,False,False,False,False,True,False,False,False,False,False,False,False
208413,serve/light/fff7c4d4be623b2939969e02ef27227059...,23,code,True,True,False,False,False,False,True,True,True,False,False,False,False,False
208423,serve/light/fffd885a4df5d69c9f709a216f25a91260...,18,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
208424,serve/light/fffe21dde7d18843cef438cd9eb13437de...,19,code,True,True,False,False,False,False,True,False,False,False,False,False,False,False
208426,serve/light/fffe21dde7d18843cef438cd9eb13437de...,27,code,True,True,False,False,False,False,True,False,False,False,False,False,False,False

In [12]:
noheading_after[(noheading_after['markdown_after'] == True)]

,fileNames,cell_seq_num,cellType,_has_output,_output_contains_graphics,_output_contains_tables,_has_heading,has_tables,has_math,markdown_before,markdown_after,before_contains_heading,before_contains_tables,before_contains_math,after_contains_heading,after_contains_tables,after_contains_math
0,serve/light/00014130779110127e4663c5bea956ca98...,18,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
2,serve/light/00014130779110127e4663c5bea956ca98...,25,code,True,True,False,False,False,False,True,True,True,False,False,False,False,False
3,serve/light/00014130779110127e4663c5bea956ca98...,27,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
4,serve/light/00014130779110127e4663c5bea956ca98...,29,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
6,serve/light/00014130779110127e4663c5bea956ca98...,35,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208408,serve/light/fff6c4a56e1a630fa61b9bd5aa9adce411...,62,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
208410,serve/light/fff6c4a56e1a630fa61b9bd5aa9adce411...,65,code,True,True,False,False,False,False,False,True,False,False,False,False,False,False
208413,serve/light/fff7c4d4be623b2939969e02ef27227059...,23,code,True,True,False,False,False,False,True,True,True,False,False,False,False,False
208423,serve/light/fffd885a4df5d69c9f709a216f25a91260...,18,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
208425,serve/light/fffe21dde7d18843cef438cd9eb13437de...,21,code,True,True,False,False,False,False,False,True,False,False,False,False,False,False

In [14]:
table_before_after = noheading_after[(noheading_after['before_contains_tables'] == True) | (noheading_after['after_contains_tables'] == True)]
table_before_after

,fileNames,cell_seq_num,cellType,_has_output,_output_contains_graphics,_output_contains_tables,_has_heading,has_tables,has_math,markdown_before,markdown_after,before_contains_heading,before_contains_tables,before_contains_math,after_contains_heading,after_contains_tables,after_contains_math
31,serve/light/00038711f68d5da6bedd8ab445da2b3a4f...,11,code,True,True,False,False,False,False,False,False,False,True,False,False,False,False
47,serve/light/000b9b614ace7998d74ba13ce98f1535e4...,3,code,True,True,False,False,False,False,False,False,False,True,False,False,False,False
122,serve/light/0027e9d12c56ee6708cfc644f74246aba6...,13,code,True,True,False,False,False,False,True,True,False,False,False,False,True,False
123,serve/light/0027e9d12c56ee6708cfc644f74246aba6...,50,code,True,True,False,False,False,False,True,True,False,False,False,False,True,False
130,serve/light/00288e4d8862445f9c2cd49ed54de74113...,49,code,True,True,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208356,serve/light/ffe485f1bb9a4b8fc38d971342b9176d71...,23,code,True,True,False,False,False,False,False,True,False,True,False,False,False,False
208357,serve/light/ffe485f1bb9a4b8fc38d971342b9176d71...,57,code,True,True,False,False,False,False,False,False,False,True,False,False,False,False
208358,serve/light/ffe485f1bb9a4b8fc38d971342b9176d71...,62,code,True,True,False,False,False,False,False,False,False,True,False,False,False,False
208373,serve/light/ffed6e9f00d7310bc9081e6559763c1d25...,13,code,True,True,False,False,False,False,False,True,False,True,False,False,False,False
208379,serve/light/ffed6e9f00d7310bc9081e6559763c1d25...,25,code,True,True,False,False,False,False,False,False,False,True,False,False,False,False

In [15]:
table_before_after['fileNames'].value_counts()

serve/light/62a67b766651d9601ee8a026ec45736dee65e238.html    46
serve/light/52e320128271fe60d3a0e17a068f83ead8dfd1ce.html    36
serve/light/fd42ef37819d8864a0988a754f7698821b92916a.html    34
serve/light/5bf5de3f1ff16696d3bf713f032bc49fa4d82ba6.html    25
serve/light/d317e0920878fa2e8ac102b7e62a1142af9567dd.html    24
                                                             ..
serve/light/6ad16aae77f712418139f94b57929bed274d231e.html     1
serve/light/6abc8b21f22b74130e83022c7bc6863f72d7f55d.html     1
serve/light/6ab846f7bad25b4fac314fcf4cd81a495b192cc9.html     1
serve/light/6ab4a535bcc83affd19b7b7412e13d7a9d32d834.html     1
serve/light/810687f826b0dd097430449a7e4ac88d149ce150.html     1
Name: fileNames, Length: 7109, dtype: int64

In [23]:
possible_manual_tables = noheading_after[
    ((noheading_after['before_contains_tables'] == True) | (noheading_after['after_contains_tables'] == True)) |
    ((noheading_after['markdown_before'] == True) | (noheading_after['markdown_after'] == True))
]
possible_manual_tables

,fileNames,cell_seq_num,cellType,_has_output,_output_contains_graphics,_output_contains_tables,_has_heading,has_tables,has_math,markdown_before,markdown_after,before_contains_heading,before_contains_tables,before_contains_math,after_contains_heading,after_contains_tables,after_contains_math
0,serve/light/00014130779110127e4663c5bea956ca98...,18,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
2,serve/light/00014130779110127e4663c5bea956ca98...,25,code,True,True,False,False,False,False,True,True,True,False,False,False,False,False
3,serve/light/00014130779110127e4663c5bea956ca98...,27,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
4,serve/light/00014130779110127e4663c5bea956ca98...,29,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
6,serve/light/00014130779110127e4663c5bea956ca98...,35,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208413,serve/light/fff7c4d4be623b2939969e02ef27227059...,23,code,True,True,False,False,False,False,True,True,True,False,False,False,False,False
208423,serve/light/fffd885a4df5d69c9f709a216f25a91260...,18,code,True,True,False,False,False,False,True,True,False,False,False,False,False,False
208424,serve/light/fffe21dde7d18843cef438cd9eb13437de...,19,code,True,True,False,False,False,False,True,False,False,False,False,False,False,False
208425,serve/light/fffe21dde7d18843cef438cd9eb13437de...,21,code,True,True,False,False,False,False,False,True,False,False,False,False,False,False
208426,serve/light/fffe21dde7d18843cef438cd9eb13437de...,27,code,True,True,False,False,False,False,True,False,False,False,False,False,False,False

In [24]:
possible_manual_tables['fileNames'].value_counts()

serve/light/72667ad2f073fa7925d83afaf7c912a4d27a4cf0.html    91
serve/light/931568140bb98f0ac04ba663174869aca591240a.html    80
serve/light/9eb0049bea949d24c754c47a74104615b87882a3.html    75
serve/light/62a67b766651d9601ee8a026ec45736dee65e238.html    63
serve/light/332d582c84a2e0d056f95ad7bf7267108176e469.html    56
                                                             ..
serve/light/34bd23893e922372b19b7cf86b1f9599409dc0dc.html     1
serve/light/99dcf9c339c924e869d5c554d64f8bce4df80e77.html     1
serve/light/34b315ac1fe73dc67ed887432d12a0fdaf1abb24.html     1
serve/light/99e397196879e3db298890218ef5ed7877142753.html     1
serve/light/7fa1f9d2811f95356d761315e4a573629111d284.html     1
Name: fileNames, Length: 22792, dtype: int64